set nocompatible              " be iMproved, required
filetype off                  " required

" set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

" let Vundle manage Vundle, required
Plugin 'gmarik/Vundle.vim'

Plugin 'Valloric/YouCompleteMe'
Plugin 'kien/ctrlp.vim'
Plugin 'scrooloose/syntastic'
Plugin 'tpope/vim-surround'
Plugin 'Raimondi/delimitMate'
Plugin 'othree/html5.vim'
Plugin 'christoomey/vim-tmux-navigator'
Plugin 'chriskempson/base16-vim'

call vundle#end()            " required

let g:ycm_global_ycm_extra_conf = '$HOME/.ycm_extra_conf.py'
let g:ycm_confirm_extra_conf = 1
let delimitMate_expand_cr = 1
let delimitMate_expand_space = 1

filetype plugin indent on 

" Change color theme
set background=dark
colorscheme base16-default
syntax on

set number
set backspace=2
set history=1000
set showmode
set gcr=a:blinkon0
set visualbell
autocmd CompleteDone * pclose

set autoread
set hidden

set wildmenu

set expandtab
set shiftround
set shiftwidth=2
set softtabstop=2
set cindent

imap jj <Esc>

set mouse=a
set clipboard=unnamed
