set nocompatible

if empty(glob('~/.vim/autoload/plug.vim'))
  silent !curl -fLo ~/.vim/autoload/plug.vim --create-dirs
    \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
  autocmd VimEnter * PlugInstall | source $MYVIMRC
endif
call plug#begin('~/.vim/plugged')

" movement
Plug 'christoomey/vim-tmux-navigator'
Plug 'justinmk/vim-sneak'

" completion
Plug 'tpope/vim-commentary'
Plug 'raimondi/delimitMate'
Plug 'ajh17/VimCompletesMe'

" file management
Plug 'junegunn/fzf', { 'dir': '~/.fzf', 'do': './install --all'  }
Plug 'junegunn/fzf.vim'
Plug 'qpkorr/vim-bufkill'
Plug 'tpope/vim-fugitive'
Plug 'ludovicchabant/vim-gutentags'

" usability
Plug 'tpope/vim-surround'
Plug 'tpope/vim-repeat'
Plug 'tpope/vim-unimpaired'
Plug 'wellle/targets.vim'
Plug 'peterrincker/vim-argumentative'

" ui
Plug 'neomake/neomake'
Plug 'mhinz/vim-signify'
Plug 'chriskempson/base16-vim'
Plug 'vim-airline/vim-airline'
Plug 'vim-airline/vim-airline-themes'

" python
Plug 'davidhalter/jedi-vim'
Plug 'hynek/vim-python-pep8-indent'

call plug#end()

" neomake config
autocmd! BufWritePost * Neomake

" jedi-vim config
let g:jedi#documentation_command = ""

" fzf config
nnoremap <c-p> :GFiles<cr>

" delimitMate config
let delimitMate_expand_cr = 1
let delimitMate_expand_space = 1

" airline config
let g:airline#extensions#tabline#enabled = 1
let g:airline#extensions#tabline#fnamemod = ':t'
let g:airline_powerline_fonts = 1
let g:airline_theme = 'base16'

filetype plugin indent on

" completion config
set omnifunc=syntaxcomplete#Complete

" Change color theme
set background=dark
let base16colorspace=256
colorscheme base16-default-dark
syntax on

map <SPACE> <leader>

" fix this by using the --query arg as the initial
nnoremap K :Ag <C-R><C-W><CR>
nnoremap <Tab> :bnext<CR>
nnoremap <S-Tab> :bprevious<CR>

" Make capital y act more normal
nnoremap Y y$

" Make saving quicker
noremap <Leader>w :w<CR>

" search options
set incsearch
set hlsearch
set smartcase

" gotta go fast
set lazyredraw
set timeoutlen=400
set ttyfast
set ttyscroll=3
hi NonText cterm=NONE ctermfg=NONE

" normal setings
set rnu
set number
set cursorline
set backspace=2
set history=1000
set showmode
set gcr=a:blinkon0
set visualbell
set ttymouse=xterm2

set hidden
set tags=./tags;
set autoread

set wildmenu

set expandtab
set shiftround
set shiftwidth=4
set softtabstop=4

set mouse=a " enable mouse

set clipboard=unnamed

" vim-sneak config
let g:sneak#streak = 1
hi link SneakPluginTarget Error
hi link SneakStreakTarget Error
hi link SneakStreakMask Error
