set nocompatible              " be improved, required

if empty(glob('~/.vim/autoload/plug.vim'))
  silent !curl -fLo ~/.vim/autoload/plug.vim --create-dirs
    \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
  autocmd VimEnter * PlugInstall | source $MYVIMRC
endif
call plug#begin('~/.vim/plugged')

Plug 'scrooloose/syntastic'
Plug 'tpope/vim-surround'
Plug 'tpope/vim-fugitive'
Plug 'tpope/vim-commentary'
Plug 'raimondi/delimitMate'
Plug 'wellle/targets.vim'
Plug 'christoomey/vim-tmux-navigator'
Plug 'chriskempson/base16-vim'
Plug 'mhinz/vim-signify'
Plug 'justinmk/vim-sneak'
Plug 'vim-airline/vim-airline'
Plug 'vim-airline/vim-airline-themes'
Plug 'ervandew/supertab'
Plug 'junegunn/fzf', { 'dir': '~/.fzf', 'do': './install --all'  }
Plug 'junegunn/fzf.vim'

call plug#end()

" fzf config
nnoremap <c-p> :GFiles<cr>

" delimitMate config
let delimitMate_expand_cr = 1
let delimitMate_expand_space = 1

" airline config
let g:airline#extensions#tabline#enabled = 1
let g:airline_powerline_fonts = 1
let g:airline_theme = 'base16'

filetype plugin indent on

" supertab config
set omnifunc=syntaxcomplete#Complete
let g:SuperTabContextDefaultCompletionType = "<c-n>"
let g:SuperTabDefaultCompletionType = "context"
let g:SuperTabClosePreviewOnPopupClose = 1
autocmd FileType *
\ if &omnifunc != '' |
\   call SuperTabChain(&omnifunc, "<c-n>") |
\ endif

" Change color theme
set background=dark
let base16colorspace=256
colorscheme base16-default-dark
syntax on

map <SPACE> <leader>
set rnu
set number
set backspace=2
set history=1000
set showmode
set gcr=a:blinkon0
set visualbell
set incsearch
set hlsearch

set autoread
set hidden
set tags=./tags;

set wildmenu

set expandtab
set shiftround
set shiftwidth=4
set softtabstop=4

imap jj <Esc>

set mouse=a " enable mouse
set ttymouse=xterm2 " enable mouse split dragging

set clipboard=unnamed
