""" BASIC COMMANDS
set nocompatible

" move by screen-line instead of text-line
nmap j gj
nmap k gk

" make capital Y act more normal
nnoremap Y y$

" easily rehighlight recently pasted text
nnoremap gp `[v`]

" search options
set incsearch
set hlsearch
set ignorecase
set smartcase

" line numbering
set relativenumber
set number

" link to system clipboard
set clipboard=unnamed

" make splits more intuitive
set splitbelow
set splitright

" turn on syntax highlighting
syntax on

""" TERMINAL SPECIFIC
set mouse=a

" gotta go fast
set lazyredraw
set timeoutlen=400
set ttyfast
set ttyscroll=3

" leader commands
noremap <Leader>w :w<CR> |" easier saving
noremap <Leader>c :let @+ = expand("%")<CR> |" copy filepath

""" PLUGINS

if empty(glob('~/.vim/autoload/plug.vim'))
  silent !curl -fLo ~/.vim/autoload/plug.vim --create-dirs
    \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
  autocmd VimEnter * PlugInstall | source $MYVIMRC
endif
call plug#begin('~/.vim/plugged')

" movement
Plug 'christoomey/vim-tmux-navigator'

" completion
Plug 'tpope/vim-commentary'
Plug 'jiangmiao/auto-pairs'
Plug 'ajh17/VimCompletesMe'
Plug 'maralla/completor.vim'

" file management
Plug 'junegunn/fzf', { 'dir': '~/.fzf', 'do': './install --all'  }
Plug 'junegunn/fzf.vim'
Plug 'qpkorr/vim-bufkill'
Plug 'tpope/vim-fugitive'
Plug 'tpope/vim-rhubarb'
Plug 'ludovicchabant/vim-gutentags'
Plug 'majutsushi/tagbar'

" usability
Plug 'tpope/vim-surround'
Plug 'tpope/vim-repeat'
Plug 'tpope/vim-unimpaired'
Plug 'wellle/targets.vim'
Plug 'peterrincker/vim-argumentative'

" ui
Plug 'w0rp/ale'
Plug 'mhinz/vim-signify'
Plug 'chriskempson/base16-vim'
Plug 'vim-airline/vim-airline'
Plug 'vim-airline/vim-airline-themes'

" python
Plug 'davidhalter/jedi-vim'
Plug 'hynek/vim-python-pep8-indent'
Plug 'jmcantrell/vim-virtualenv'

" javascript
Plug 'pangloss/vim-javascript'

" other filetypes
Plug 'chrisbra/csv.vim'

call plug#end()

" bufkill config
nmap <C-c> :BD<CR>

" ale config
let g:ale_lint_on_text_changed = 0
let g:ale_lint_on_save = 1

" jedi-vim config
let g:jedi#documentation_command = ""

" fzf config
nnoremap <c-p> :GFiles<cr>

" tagbar config
noremap <Leader>t :TagbarToggle<CR>
autocmd FileType tagbar setlocal nocursorline nocursorcolumn

" delimitMate config
let delimitMate_expand_cr = 1
let delimitMate_expand_space = 1

" airline config
let g:airline#extensions#tabline#enabled = 1
let g:airline#extensions#tabline#fnamemod = ':t'
let g:airline_theme = 'base16'

filetype plugin indent on

" completion config
set omnifunc=syntaxcomplete#Complete
let b:vcm_tab_complete = 'omni'

" Change color theme
set background=dark
let base16colorspace=256
colorscheme base16-default-dark

map <SPACE> <leader>

" fix this by using the --query arg as the initial
nnoremap K :Ag <C-R><C-W><CR>

" normal setings
set cursorline
set backspace=2
set history=1000
set showmode
set gcr=a:blinkon0
set visualbell
set ttymouse=xterm2

set hidden
set tags=./tags;
set autoread

set wildmenu

set expandtab
set shiftround
set shiftwidth=4
set softtabstop=4

" autocmds
autocmd BufNewFile,BufRead *.sls  set syntax=yaml
