#!/usr/bin/env zsh

# put completions in .zfunc
fpath+="$HOME/.zfunc"
autoload -Uz compinit
compinit

export XDG_CONFIG_HOME="$HOME/.config"

HISTFILE=$XDG_CONFIG_HOME/zsh/histfile
export PATH="$HOME/bin:$PATH"
export GOPATH=$HOME/src
export GO111MODULE='on'
export PYTHONBREAKPOINT=ipdb.set_trace
export PATH=$PATH:$GOPATH/bin
export PATH="$PATH:$HOME/.local/bin"
export PATH="/usr/local/sbin:$PATH"
export PATH="/usr/local/opt/llvm/bin:$PATH"
export PATH="/usr/local/opt/ruby/bin:$PATH"
export PATH="/usr/local/lib/ruby/gems/2.7.0/bin:$PATH"
export PATH="/usr/local/opt/libxml2/bin:$PATH"
export CLANG_FORMAT="clang-format"
export WEECHAT_HOME="$XDG_CONFIG_HOME/weechat"
alias bazel=bazelisk
HISTSIZE=10000000
SAVEHIST=1000000
setopt autocd extendedglob
setopt INC_APPEND_HISTORY
setopt CLOBBER
bindkey -e

#ruby things
# eval "$(rbenv init -)"

# node things
eval "$(fnm env)"

TERM=xterm-256color
if [ -z "$NVIM_LISTEN_ADDRESS" ]; then
    export VISUAL="$(which nvim)"
fi

# fzf
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
export FZF_DEFAULT_OPTS="--ansi --no-height"
export FZF_DEFAULT_COMMAND='rg --files'
export FZF_CTRL_T_COMMAND="$FZF_DEFAULT_COMMAND"
export FZF_CTRL_T_OPTS="--preview 'bat --color=always {}'"

if [ -d "$HOME/.kube"  ]; then
    kubeconfigs=$(find "$HOME/.kube" -maxdepth 1 -type f | paste -sd ':' -)
    export KUBECONFIG="$KUBECONFIG:$kubeconfigs"
fi

# lyft
export PROJECT_ROOT="$HOME/src"
if [ -f ~/.lyftrc  ]; then
    source ~/.lyftrc
fi

. $XDG_CONFIG_HOME/zsh/alias.sh
. $XDG_CONFIG_HOME/zsh/theme.sh
. $XDG_CONFIG_HOME/zsh/functions.sh
PATH=$PATH:/Users/mgrossman/.lyftkube-bin

source /usr/local/share/zsh-autosuggestions/zsh-autosuggestions.zsh
source /usr/local/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
source '/Users/mgrossman/.sh/custom/npm-logout.sh'
