export XDG_CONFIG_HOME="$HOME/.config"

HISTFILE=$XDG_CONFIG_HOME/zsh/histfile
HISTSIZE=1000000
SAVEHIST=1000000
setopt autocd extendedglob
setopt INC_APPEND_HISTORY
setopt CLOBBER
bindkey -e

source /usr/local/share/zsh-autosuggestions/zsh-autosuggestions.zsh
source /usr/local/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
export EDITOR=`which nvim`

# fzf
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
export FZF_DEFAULT_COMMAND='rg --files'
export FZF_CTRL_T_COMMAND="$FZF_DEFAULT_COMMAND"
export FZF_DEFAULT_OPTS="--ansi --no-height"

# lyft
if [ -f ~/.lyftrc  ]; then
    source ~/.lyftrc
fi

. $XDG_CONFIG_HOME/zsh/alias.sh
. $XDG_CONFIG_HOME/zsh/theme.zsh
. $XDG_CONFIG_HOME/zsh/functions.zsh
source '/Users/mgrossman/src/blessclient/lyftprofile' # bless ssh alias
