export XDG_CONFIG_HOME="$HOME/.config"

HISTFILE=$XDG_CONFIG_HOME/zsh/histfile
HISTSIZE=100000
SAVEHIST=100000
setopt autocd extendedglob
setopt INC_APPEND_HISTORY
setopt CLOBBER
bindkey -e

# fzf
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
export FZF_DEFAULT_COMMAND='ag -g ""'
export FZF_CTRL_T_COMMAND="$FZF_DEFAULT_COMMAND"
export FZF_DEFAULT_OPTS="--ansi --sort --no-height"

# lyft
if [ -f ~/.lyftrc  ]; then
    source ~/.lyftrc
    source '/Users/mgrossman/src/blessclient/lyftprofile' # bless ssh alias
fi

. $XDG_CONFIG_HOME/zsh/alias.sh
. $XDG_CONFIG_HOME/zsh/theme.zsh
. $XDG_CONFIG_HOME/zsh/functions.zsh
